import { Controller, Get } from '@nestjs/common';

const divisionData = [
  {
    division: 'Organic Vegetables',
    transactions: [
      {
        TransactionID: 'OVT001',
        Division: 'Organic Vegetables',
        Date: '2024-01-01',
        Supplier: 'FertileGrow Inc.',
        Item: 'Organic Fertilizer A',
        Quantity: 1000,
        UnitPrice: 50,
        TotalPrice: 50000,
        Notes: 'Monthly supply for spring crops',
      },
      {
        TransactionID: 'OVT002',
        Division: 'Organic Vegetables',
        Date: '2024-01-02',
        Supplier: 'GreenBoost LLC',
        Item: 'Organic Fertilizer B',
        Quantity: 800,
        UnitPrice: 60,
        TotalPrice: 48000,
        Notes: 'Additional supply for summer crops',
      },
      {
        TransactionID: 'OVT003',
        Division: 'Organic Vegetables',
        Date: '2024-01-03',
        Supplier: 'EcoFertilizer Co.',
        Item: 'Organic Fertilizer C',
        Quantity: 600,
        UnitPrice: 70,
        TotalPrice: 42000,
        Notes: 'Special blend for high yield',
      },
      {
        TransactionID: 'OVT004',
        Division: 'Organic Vegetables',
        Date: '2024-01-04',
        Supplier: 'FertileGrow Inc.',
        Item: 'Organic Fertilizer A',
        Quantity: 1200,
        UnitPrice: 50,
        TotalPrice: 60000,
        Notes: 'Monthly supply for summer crops',
      },
      {
        TransactionID: 'OVT005',
        Division: 'Organic Vegetables',
        Date: '2024-01-05',
        Supplier: 'GreenBoost LLC',
        Item: 'Organic Fertilizer B',
        Quantity: 900,
        UnitPrice: 60,
        TotalPrice: 54000,
        Notes: 'Monthly supply for autumn crops',
      },
      {
        TransactionID: 'OVT006',
        Division: 'Organic Vegetables',
        Date: '2024-01-06',
        Supplier: 'EcoFertilizer Co.',
        Item: 'Organic Fertilizer C',
        Quantity: 700,
        UnitPrice: 70,
        TotalPrice: 49000,
        Notes: 'Special blend for root crops',
      },
      {
        TransactionID: 'OVT007',
        Division: 'Organic Vegetables',
        Date: '2024-01-07',
        Supplier: 'FertileGrow Inc.',
        Item: 'Organic Fertilizer A',
        Quantity: 1100,
        UnitPrice: 52,
        TotalPrice: 57200,
        Notes: 'Monthly supply for spring crops',
      },
      {
        TransactionID: 'OVT008',
        Division: 'Organic Vegetables',
        Date: '2024-01-08',
        Supplier: 'GreenBoost LLC',
        Item: 'Organic Fertilizer B',
        Quantity: 850,
        UnitPrice: 62,
        TotalPrice: 52700,
        Notes: 'Additional supply for summer crops',
      },
      {
        TransactionID: 'OVT009',
        Division: 'Organic Vegetables',
        Date: '2024-01-09',
        Supplier: 'EcoFertilizer Co.',
        Item: 'Organic Fertilizer C',
        Quantity: 650,
        UnitPrice: 72,
        TotalPrice: 46800,
        Notes: 'Special blend for high yield',
      },
      {
        TransactionID: 'OVT010',
        Division: 'Organic Vegetables',
        Date: '2024-01-10',
        Supplier: 'FertileGrow Inc.',
        Item: 'Organic Fertilizer A',
        Quantity: 1300,
        UnitPrice: 54,
        TotalPrice: 70200,
        Notes: 'Monthly supply for summer crops',
      },
      {
        TransactionID: 'OVT011',
        Division: 'Organic Vegetables',
        Date: '2024-01-11',
        Supplier: 'GreenBoost LLC',
        Item: 'Organic Fertilizer B',
        Quantity: 950,
        UnitPrice: 64,
        TotalPrice: 60800,
        Notes: 'Monthly supply for autumn crops',
      },
      {
        TransactionID: 'OVT012',
        Division: 'Organic Vegetables',
        Date: '2024-01-12',
        Supplier: 'EcoFertilizer Co.',
        Item: 'Organic Fertilizer C',
        Quantity: 750,
        UnitPrice: 74,
        TotalPrice: 55500,
        Notes: 'Special blend for root crops',
      },
      {
        TransactionID: 'OVT013',
        Division: 'Organic Vegetables',
        Date: '2024-01-13',
        Supplier: 'FertileGrow Inc.',
        Item: 'Organic Fertilizer A',
        Quantity: 1150,
        UnitPrice: 56,
        TotalPrice: 64400,
        Notes: 'Monthly supply for spring crops',
      },
      {
        TransactionID: 'OVT014',
        Division: 'Organic Vegetables',
        Date: '2024-01-14',
        Supplier: 'GreenBoost LLC',
        Item: 'Organic Fertilizer B',
        Quantity: 900,
        UnitPrice: 66,
        TotalPrice: 59400,
        Notes: 'Additional supply for summer crops',
      },
      {
        TransactionID: 'OVT015',
        Division: 'Organic Vegetables',
        Date: '2024-01-15',
        Supplier: 'EcoFertilizer Co.',
        Item: 'Organic Fertilizer C',
        Quantity: 700,
        UnitPrice: 76,
        TotalPrice: 53200,
        Notes: 'Special blend for high yield',
      },
      {
        TransactionID: 'OVT016',
        Division: 'Organic Vegetables',
        Date: '2024-01-16',
        Supplier: 'FertileGrow Inc.',
        Item: 'Organic Fertilizer A',
        Quantity: 1250,
        UnitPrice: 58,
        TotalPrice: 72500,
        Notes: 'Monthly supply for summer crops',
      },
      {
        TransactionID: 'OVT017',
        Division: 'Organic Vegetables',
        Date: '2024-01-17',
        Supplier: 'GreenBoost LLC',
        Item: 'Organic Fertilizer B',
        Quantity: 950,
        UnitPrice: 68,
        TotalPrice: 64600,
        Notes: 'Monthly supply for autumn crops',
      },
      {
        TransactionID: 'OVT018',
        Division: 'Organic Vegetables',
        Date: '2024-01-18',
        Supplier: 'EcoFertilizer Co.',
        Item: 'Organic Fertilizer C',
        Quantity: 750,
        UnitPrice: 78,
        TotalPrice: 58500,
        Notes: 'Special blend for root crops',
      },
      {
        TransactionID: 'OVT019',
        Division: 'Organic Vegetables',
        Date: '2024-01-19',
        Supplier: 'FertileGrow Inc.',
        Item: 'Organic Fertilizer A',
        Quantity: 1200,
        UnitPrice: 60,
        TotalPrice: 72000,
        Notes: 'Monthly supply for spring crops',
      },
      {
        TransactionID: 'OVT020',
        Division: 'Organic Vegetables',
        Date: '2024-01-20',
        Supplier: 'GreenBoost LLC',
        Item: 'Organic Fertilizer B',
        Quantity: 1000,
        UnitPrice: 70,
        TotalPrice: 70000,
        Notes: 'Additional supply for summer crops',
      },
      {
        TransactionID: 'OVT021',
        Division: 'Organic Vegetables',
        Date: '2024-01-21',
        Supplier: 'EcoFertilizer Co.',
        Item: 'Organic Fertilizer C',
        Quantity: 800,
        UnitPrice: 80,
        TotalPrice: 64000,
        Notes: 'Special blend for high yield',
      },
      {
        TransactionID: 'OVT022',
        Division: 'Organic Vegetables',
        Date: '2024-01-22',
        Supplier: 'FertileGrow Inc.',
        Item: 'Organic Fertilizer A',
        Quantity: 1300,
        UnitPrice: 62,
        TotalPrice: 80600,
        Notes: 'Monthly supply for summer crops',
      },
      {
        TransactionID: 'OVT023',
        Division: 'Organic Vegetables',
        Date: '2024-01-23',
        Supplier: 'GreenBoost LLC',
        Item: 'Organic Fertilizer B',
        Quantity: 1050,
        UnitPrice: 72,
        TotalPrice: 75600,
        Notes: 'Monthly supply for autumn crops',
      },
      {
        TransactionID: 'OVT024',
        Division: 'Organic Vegetables',
        Date: '2024-01-24',
        Supplier: 'EcoFertilizer Co.',
        Item: 'Organic Fertilizer C',
        Quantity: 850,
        UnitPrice: 82,
        TotalPrice: 69700,
        Notes: 'Special blend for root crops',
      },
      {
        TransactionID: 'OVT025',
        Division: 'Organic Vegetables',
        Date: '2024-01-25',
        Supplier: 'FertileGrow Inc.',
        Item: 'Organic Fertilizer A',
        Quantity: 1250,
        UnitPrice: 64,
        TotalPrice: 80000,
        Notes: 'Monthly supply for spring crops',
      },
      {
        TransactionID: 'OVT026',
        Division: 'Organic Vegetables',
        Date: '2024-01-26',
        Supplier: 'GreenBoost LLC',
        Item: 'Organic Fertilizer B',
        Quantity: 1100,
        UnitPrice: 74,
        TotalPrice: 81400,
        Notes: 'Additional supply for summer crops',
      },
      {
        TransactionID: 'OVT027',
        Division: 'Organic Vegetables',
        Date: '2024-01-27',
        Supplier: 'EcoFertilizer Co.',
        Item: 'Organic Fertilizer C',
        Quantity: 900,
        UnitPrice: 84,
        TotalPrice: 75600,
        Notes: 'Special blend for high yield',
      },
      {
        TransactionID: 'OVT028',
        Division: 'Organic Vegetables',
        Date: '2024-01-28',
        Supplier: 'FertileGrow Inc.',
        Item: 'Organic Fertilizer A',
        Quantity: 1350,
        UnitPrice: 66,
        TotalPrice: 89100,
        Notes: 'Monthly supply for summer crops',
      },
      {
        TransactionID: 'OVT029',
        Division: 'Organic Vegetables',
        Date: '2024-01-29',
        Supplier: 'GreenBoost LLC',
        Item: 'Organic Fertilizer B',
        Quantity: 1150,
        UnitPrice: 76,
        TotalPrice: 87400,
        Notes: 'Monthly supply for autumn crops',
      },
      {
        TransactionID: 'OVT030',
        Division: 'Organic Vegetables',
        Date: '2024-01-30',
        Supplier: 'EcoFertilizer Co.',
        Item: 'Organic Fertilizer C',
        Quantity: 950,
        UnitPrice: 86,
        TotalPrice: 81700,
        Notes: 'Special blend for root crops',
      },
      {
        TransactionID: 'OVT031',
        Division: 'Organic Vegetables',
        Date: '2024-01-31',
        Supplier: 'FertileGrow Inc.',
        Item: 'Organic Fertilizer A',
        Quantity: 1400,
        UnitPrice: 68,
        TotalPrice: 95200,
        Notes: 'Monthly supply for spring crops',
      },
      {
        TransactionID: 'OVT032',
        Division: 'Organic Vegetables',
        Date: '2024-02-01',
        Supplier: 'GreenBoost LLC',
        Item: 'Organic Fertilizer B',
        Quantity: 1200,
        UnitPrice: 78,
        TotalPrice: 93600,
        Notes: 'Additional supply for summer crops',
      },
      {
        TransactionID: 'OVT033',
        Division: 'Organic Vegetables',
        Date: '2024-02-02',
        Supplier: 'EcoFertilizer Co.',
        Item: 'Organic Fertilizer C',
        Quantity: 1000,
        UnitPrice: 88,
        TotalPrice: 88000,
        Notes: 'Special blend for high yield',
      },
      {
        TransactionID: 'OVT034',
        Division: 'Organic Vegetables',
        Date: '2024-02-03',
        Supplier: 'FertileGrow Inc.',
        Item: 'Organic Fertilizer A',
        Quantity: 1450,
        UnitPrice: 70,
        TotalPrice: 101500,
        Notes: 'Monthly supply for summer crops',
      },
      {
        TransactionID: 'OVT035',
        Division: 'Organic Vegetables',
        Date: '2024-02-04',
        Supplier: 'GreenBoost LLC',
        Item: 'Organic Fertilizer B',
        Quantity: 1250,
        UnitPrice: 80,
        TotalPrice: 100000,
        Notes: 'Monthly supply for autumn crops',
      },
      {
        TransactionID: 'OVT036',
        Division: 'Organic Vegetables',
        Date: '2024-02-05',
        Supplier: 'EcoFertilizer Co.',
        Item: 'Organic Fertilizer C',
        Quantity: 1050,
        UnitPrice: 90,
        TotalPrice: 94500,
        Notes: 'Special blend for root crops',
      },
      {
        TransactionID: 'OVT037',
        Division: 'Organic Vegetables',
        Date: '2024-02-06',
        Supplier: 'FertileGrow Inc.',
        Item: 'Organic Fertilizer A',
        Quantity: 1500,
        UnitPrice: 72,
        TotalPrice: 108000,
        Notes: 'Monthly supply for spring crops',
      },
      {
        TransactionID: 'OVT038',
        Division: 'Organic Vegetables',
        Date: '2024-02-07',
        Supplier: 'GreenBoost LLC',
        Item: 'Organic Fertilizer B',
        Quantity: 1300,
        UnitPrice: 82,
        TotalPrice: 106600,
        Notes: 'Additional supply for summer crops',
      },
      {
        TransactionID: 'OVT039',
        Division: 'Organic Vegetables',
        Date: '2024-02-08',
        Supplier: 'EcoFertilizer Co.',
        Item: 'Organic Fertilizer C',
        Quantity: 1100,
        UnitPrice: 92,
        TotalPrice: 101200,
        Notes: 'Special blend for high yield',
      },
      {
        TransactionID: 'OVT040',
        Division: 'Organic Vegetables',
        Date: '2024-02-09',
        Supplier: 'FertileGrow Inc.',
        Item: 'Organic Fertilizer A',
        Quantity: 1550,
        UnitPrice: 74,
        TotalPrice: 114700,
        Notes: 'Monthly supply for summer crops',
      },
      {
        TransactionID: 'OVT041',
        Division: 'Organic Vegetables',
        Date: '2024-02-10',
        Supplier: 'GreenBoost LLC',
        Item: 'Organic Fertilizer B',
        Quantity: 1350,
        UnitPrice: 84,
        TotalPrice: 113400,
        Notes: 'Monthly supply for autumn crops',
      },
      {
        TransactionID: 'OVT042',
        Division: 'Organic Vegetables',
        Date: '2024-02-11',
        Supplier: 'EcoFertilizer Co.',
        Item: 'Organic Fertilizer C',
        Quantity: 1150,
        UnitPrice: 94,
        TotalPrice: 108100,
        Notes: 'Special blend for root crops',
      },
      {
        TransactionID: 'OVT043',
        Division: 'Organic Vegetables',
        Date: '2024-02-12',
        Supplier: 'FertileGrow Inc.',
        Item: 'Organic Fertilizer A',
        Quantity: 1600,
        UnitPrice: 76,
        TotalPrice: 121600,
        Notes: 'Monthly supply for spring crops',
      },
      {
        TransactionID: 'OVT044',
        Division: 'Organic Vegetables',
        Date: '2024-02-13',
        Supplier: 'GreenBoost LLC',
        Item: 'Organic Fertilizer B',
        Quantity: 1400,
        UnitPrice: 86,
        TotalPrice: 120400,
        Notes: 'Additional supply for summer crops',
      },
      {
        TransactionID: 'OVT045',
        Division: 'Organic Vegetables',
        Date: '2024-02-14',
        Supplier: 'EcoFertilizer Co.',
        Item: 'Organic Fertilizer C',
        Quantity: 1200,
        UnitPrice: 96,
        TotalPrice: 115200,
        Notes: 'Special blend for high yield',
      },
      {
        TransactionID: 'OVT046',
        Division: 'Organic Vegetables',
        Date: '2024-02-15',
        Supplier: 'FertileGrow Inc.',
        Item: 'Organic Fertilizer A',
        Quantity: 1650,
        UnitPrice: 78,
        TotalPrice: 128700,
        Notes: 'Monthly supply for summer crops',
      },
      {
        TransactionID: 'OVT047',
        Division: 'Organic Vegetables',
        Date: '2024-02-16',
        Supplier: 'GreenBoost LLC',
        Item: 'Organic Fertilizer B',
        Quantity: 1450,
        UnitPrice: 88,
        TotalPrice: 127600,
        Notes: 'Monthly supply for autumn crops',
      },
      {
        TransactionID: 'OVT048',
        Division: 'Organic Vegetables',
        Date: '2024-02-17',
        Supplier: 'EcoFertilizer Co.',
        Item: 'Organic Fertilizer C',
        Quantity: 1250,
        UnitPrice: 98,
        TotalPrice: 122500,
        Notes: 'Special blend for root crops',
      },
    ],
  },
  {
    division: 'Organic Fruits',
    transactions: [
      {
        TransactionID: 'OFT001',
        Division: 'Organic Fruits',
        Date: '2024-01-01',
        Supplier: 'FertileGrow Inc.',
        Item: 'Organic Fertilizer A',
        Quantity: 1200,
        UnitPrice: 50 * 2,
        TotalPrice: 60000 * 2,
        Notes: 'Monthly supply for spring orchards',
      },
      {
        TransactionID: 'OFT002',
        Division: 'Organic Fruits',
        Date: '2024-01-02',
        Supplier: 'GreenBoost LLC',
        Item: 'Organic Fertilizer B',
        Quantity: 900,
        UnitPrice: 60 * 2,
        TotalPrice: 54000 * 2,
        Notes: 'Additional supply for summer orchards',
      },
      {
        TransactionID: 'OFT003',
        Division: 'Organic Fruits',
        Date: '2024-01-03',
        Supplier: 'EcoFertilizer Co.',
        Item: 'Organic Fertilizer C',
        Quantity: 700,
        UnitPrice: 70 * 2,
        TotalPrice: 49000 * 2,
        Notes: 'Special blend for fruit yield',
      },
      {
        TransactionID: 'OFT004',
        Division: 'Organic Fruits',
        Date: '2024-01-04',
        Supplier: 'FertileGrow Inc.',
        Item: 'Organic Fertilizer A',
        Quantity: 1300,
        UnitPrice: 50 * 2,
        TotalPrice: 65000 * 2,
        Notes: 'Monthly supply for summer orchards',
      },
      {
        TransactionID: 'OFT005',
        Division: 'Organic Fruits',
        Date: '2024-01-05',
        Supplier: 'GreenBoost LLC',
        Item: 'Organic Fertilizer B',
        Quantity: 950,
        UnitPrice: 60 * 2,
        TotalPrice: 57000 * 2,
        Notes: 'Monthly supply for autumn orchards',
      },
      {
        TransactionID: 'OFT006',
        Division: 'Organic Fruits',
        Date: '2024-01-06',
        Supplier: 'EcoFertilizer Co.',
        Item: 'Organic Fertilizer C',
        Quantity: 750,
        UnitPrice: 70 * 2,
        TotalPrice: 52500 * 2,
        Notes: 'Special blend for citrus fruits',
      },
      {
        TransactionID: 'OFT007',
        Division: 'Organic Fruits',
        Date: '2024-01-07',
        Supplier: 'FertileGrow Inc.',
        Item: 'Organic Fertilizer A',
        Quantity: 1250,
        UnitPrice: 52 * 2,
        TotalPrice: 65000 * 2,
        Notes: 'Monthly supply for spring orchards',
      },
      {
        TransactionID: 'OFT008',
        Division: 'Organic Fruits',
        Date: '2024-01-08',
        Supplier: 'GreenBoost LLC',
        Item: 'Organic Fertilizer B',
        Quantity: 950,
        UnitPrice: 62 * 2,
        TotalPrice: 58900 * 2,
        Notes: 'Additional supply for summer orchards',
      },
      {
        TransactionID: 'OFT009',
        Division: 'Organic Fruits',
        Date: '2024-01-09',
        Supplier: 'EcoFertilizer Co.',
        Item: 'Organic Fertilizer C',
        Quantity: 800,
        UnitPrice: 72 * 2,
        TotalPrice: 57600 * 2,
        Notes: 'Special blend for fruit yield',
      },
      {
        TransactionID: 'OFT010',
        Division: 'Organic Fruits',
        Date: '2024-01-10',
        Supplier: 'FertileGrow Inc.',
        Item: 'Organic Fertilizer A',
        Quantity: 1350,
        UnitPrice: 54 * 2,
        TotalPrice: 72900 * 2,
        Notes: 'Monthly supply for summer orchards',
      },
      {
        TransactionID: 'OFT011',
        Division: 'Organic Fruits',
        Date: '2024-01-11',
        Supplier: 'GreenBoost LLC',
        Item: 'Organic Fertilizer B',
        Quantity: 1000,
        UnitPrice: 64 * 2,
        TotalPrice: 64000 * 2,
        Notes: 'Monthly supply for autumn orchards',
      },
      {
        TransactionID: 'OFT012',
        Division: 'Organic Fruits',
        Date: '2024-01-12',
        Supplier: 'EcoFertilizer Co.',
        Item: 'Organic Fertilizer C',
        Quantity: 850,
        UnitPrice: 74 * 2,
        TotalPrice: 62900 * 2,
        Notes: 'Special blend for citrus fruits',
      },
      {
        TransactionID: 'OFT013',
        Division: 'Organic Fruits',
        Date: '2024-01-13',
        Supplier: 'FertileGrow Inc.',
        Item: 'Organic Fertilizer A',
        Quantity: 1400,
        UnitPrice: 56 * 2,
        TotalPrice: 78400 * 2,
        Notes: 'Monthly supply for spring orchards',
      },
      {
        TransactionID: 'OFT014',
        Division: 'Organic Fruits',
        Date: '2024-01-14',
        Supplier: 'GreenBoost LLC',
        Item: 'Organic Fertilizer B',
        Quantity: 1050,
        UnitPrice: 66 * 2,
        TotalPrice: 69300 * 2,
        Notes: 'Additional supply for summer orchards',
      },
      {
        TransactionID: 'OFT015',
        Division: 'Organic Fruits',
        Date: '2024-01-15',
        Supplier: 'EcoFertilizer Co.',
        Item: 'Organic Fertilizer C',
        Quantity: 900,
        UnitPrice: 76 * 2,
        TotalPrice: 68400 * 2,
        Notes: 'Special blend for fruit yield',
      },
      {
        TransactionID: 'OFT016',
        Division: 'Organic Fruits',
        Date: '2024-01-16',
        Supplier: 'FertileGrow Inc.',
        Item: 'Organic Fertilizer A',
        Quantity: 1450,
        UnitPrice: 58 * 2,
        TotalPrice: 84100 * 2,
        Notes: 'Monthly supply for summer orchards',
      },
      {
        TransactionID: 'OFT017',
        Division: 'Organic Fruits',
        Date: '2024-01-17',
        Supplier: 'GreenBoost LLC',
        Item: 'Organic Fertilizer B',
        Quantity: 1100,
        UnitPrice: 68 * 2,
        TotalPrice: 74800 * 2,
        Notes: 'Monthly supply for autumn orchards',
      },
      {
        TransactionID: 'OFT018',
        Division: 'Organic Fruits',
        Date: '2024-01-18',
        Supplier: 'EcoFertilizer Co.',
        Item: 'Organic Fertilizer C',
        Quantity: 950,
        UnitPrice: 78 * 2,
        TotalPrice: 74100 * 2,
        Notes: 'Special blend for citrus fruits',
      },
      {
        TransactionID: 'OFT019',
        Division: 'Organic Fruits',
        Date: '2024-01-19',
        Supplier: 'FertileGrow Inc.',
        Item: 'Organic Fertilizer A',
        Quantity: 1500,
        UnitPrice: 60 * 2,
        TotalPrice: 90000 * 2,
        Notes: 'Monthly supply for spring orchards',
      },
      {
        TransactionID: 'OFT020',
        Division: 'Organic Fruits',
        Date: '2024-01-20',
        Supplier: 'GreenBoost LLC',
        Item: 'Organic Fertilizer B',
        Quantity: 1150,
        UnitPrice: 70 * 2,
        TotalPrice: 80500 * 2,
        Notes: 'Additional supply for summer orchards',
      },
      {
        TransactionID: 'OFT021',
        Division: 'Organic Fruits',
        Date: '2024-01-21',
        Supplier: 'EcoFertilizer Co.',
        Item: 'Organic Fertilizer C',
        Quantity: 1000,
        UnitPrice: 80 * 2,
        TotalPrice: 80000 * 2,
        Notes: 'Special blend for fruit yield',
      },
      {
        TransactionID: 'OFT022',
        Division: 'Organic Fruits',
        Date: '2024-01-22',
        Supplier: 'FertileGrow Inc.',
        Item: 'Organic Fertilizer A',
        Quantity: 1550,
        UnitPrice: 62 * 2,
        TotalPrice: 96100 * 2,
        Notes: 'Monthly supply for summer orchards',
      },
      {
        TransactionID: 'OFT023',
        Division: 'Organic Fruits',
        Date: '2024-01-23',
        Supplier: 'GreenBoost LLC',
        Item: 'Organic Fertilizer B',
        Quantity: 1200,
        UnitPrice: 72 * 2,
        TotalPrice: 86400 * 2,
        Notes: 'Monthly supply for autumn orchards',
      },
      {
        TransactionID: 'OFT024',
        Division: 'Organic Fruits',
        Date: '2024-01-24',
        Supplier: 'EcoFertilizer Co.',
        Item: 'Organic Fertilizer C',
        Quantity: 1050,
        UnitPrice: 82 * 2,
        TotalPrice: 86100 * 2,
        Notes: 'Special blend for citrus fruits',
      },
      {
        TransactionID: 'OFT025',
        Division: 'Organic Fruits',
        Date: '2024-01-25',
        Supplier: 'FertileGrow Inc.',
        Item: 'Organic Fertilizer A',
        Quantity: 1600,
        UnitPrice: 64 * 2,
        TotalPrice: 102400 * 2,
        Notes: 'Monthly supply for spring orchards',
      },
      {
        TransactionID: 'OFT026',
        Division: 'Organic Fruits',
        Date: '2024-01-26',
        Supplier: 'GreenBoost LLC',
        Item: 'Organic Fertilizer B',
        Quantity: 1250,
        UnitPrice: 74 * 2,
        TotalPrice: 92500 * 2,
        Notes: 'Additional supply for summer orchards',
      },
      {
        TransactionID: 'OFT027',
        Division: 'Organic Fruits',
        Date: '2024-01-27',
        Supplier: 'EcoFertilizer Co.',
        Item: 'Organic Fertilizer C',
        Quantity: 1100,
        UnitPrice: 84 * 2,
        TotalPrice: 92400 * 2,
        Notes: 'Special blend for fruit yield',
      },
      {
        TransactionID: 'OFT028',
        Division: 'Organic Fruits',
        Date: '2024-01-28',
        Supplier: 'FertileGrow Inc.',
        Item: 'Organic Fertilizer A',
        Quantity: 1650,
        UnitPrice: 66 * 2,
        TotalPrice: 108900 * 2,
        Notes: 'Monthly supply for summer orchards',
      },
      {
        TransactionID: 'OFT029',
        Division: 'Organic Fruits',
        Date: '2024-01-29',
        Supplier: 'GreenBoost LLC',
        Item: 'Organic Fertilizer B',
        Quantity: 1300,
        UnitPrice: 76 * 2,
        TotalPrice: 98800 * 2,
        Notes: 'Monthly supply for autumn orchards',
      },
      {
        TransactionID: 'OFT030',
        Division: 'Organic Fruits',
        Date: '2024-01-30',
        Supplier: 'EcoFertilizer Co.',
        Item: 'Organic Fertilizer C',
        Quantity: 1150,
        UnitPrice: 86 * 2,
        TotalPrice: 98900 * 2,
        Notes: 'Special blend for citrus fruits',
      },
      {
        TransactionID: 'OFT031',
        Division: 'Organic Fruits',
        Date: '2024-01-31',
        Supplier: 'FertileGrow Inc.',
        Item: 'Organic Fertilizer A',
        Quantity: 1700,
        UnitPrice: 68 * 2,
        TotalPrice: 115600 * 2,
        Notes: 'Monthly supply for spring orchards',
      },
      {
        TransactionID: 'OFT032',
        Division: 'Organic Fruits',
        Date: '2024-02-01',
        Supplier: 'GreenBoost LLC',
        Item: 'Organic Fertilizer B',
        Quantity: 1350,
        UnitPrice: 78 * 2,
        TotalPrice: 105300 * 2,
        Notes: 'Additional supply for summer orchards',
      },
      {
        TransactionID: 'OFT033',
        Division: 'Organic Fruits',
        Date: '2024-02-02',
        Supplier: 'EcoFertilizer Co.',
        Item: 'Organic Fertilizer C',
        Quantity: 1200,
        UnitPrice: 88 * 2,
        TotalPrice: 105600 * 2,
        Notes: 'Special blend for fruit yield',
      },
      {
        TransactionID: 'OFT034',
        Division: 'Organic Fruits',
        Date: '2024-02-03',
        Supplier: 'FertileGrow Inc.',
        Item: 'Organic Fertilizer A',
        Quantity: 1750,
        UnitPrice: 70 * 2,
        TotalPrice: 122500 * 2,
        Notes: 'Monthly supply for summer orchards',
      },
      {
        TransactionID: 'OFT035',
        Division: 'Organic Fruits',
        Date: '2024-02-04',
        Supplier: 'GreenBoost LLC',
        Item: 'Organic Fertilizer B',
        Quantity: 1400,
        UnitPrice: 80 * 2,
        TotalPrice: 112000 * 2,
        Notes: 'Monthly supply for autumn orchards',
      },
      {
        TransactionID: 'OFT036',
        Division: 'Organic Fruits',
        Date: '2024-02-05',
        Supplier: 'EcoFertilizer Co.',
        Item: 'Organic Fertilizer C',
        Quantity: 1250,
        UnitPrice: 90 * 2,
        TotalPrice: 112500 * 2,
        Notes: 'Special blend for citrus fruits',
      },
      {
        TransactionID: 'OFT037',
        Division: 'Organic Fruits',
        Date: '2024-02-06',
        Supplier: 'FertileGrow Inc.',
        Item: 'Organic Fertilizer A',
        Quantity: 1800,
        UnitPrice: 72 * 2,
        TotalPrice: 129600 * 2,
        Notes: 'Monthly supply for spring orchards',
      },
      {
        TransactionID: 'OFT038',
        Division: 'Organic Fruits',
        Date: '2024-02-07',
        Supplier: 'GreenBoost LLC',
        Item: 'Organic Fertilizer B',
        Quantity: 1450,
        UnitPrice: 82 * 2,
        TotalPrice: 118900 * 2,
        Notes: 'Additional supply for summer orchards',
      },
      {
        TransactionID: 'OFT039',
        Division: 'Organic Fruits',
        Date: '2024-02-08',
        Supplier: 'EcoFertilizer Co.',
        Item: 'Organic Fertilizer C',
        Quantity: 1300,
        UnitPrice: 92 * 2,
        TotalPrice: 119600 * 2,
        Notes: 'Special blend for fruit yield',
      },
      {
        TransactionID: 'OFT040',
        Division: 'Organic Fruits',
        Date: '2024-02-09',
        Supplier: 'FertileGrow Inc.',
        Item: 'Organic Fertilizer A',
        Quantity: 1850,
        UnitPrice: 74 * 2,
        TotalPrice: 136900 * 2,
        Notes: 'Monthly supply for summer orchards',
      },
      {
        TransactionID: 'OFT041',
        Division: 'Organic Fruits',
        Date: '2024-02-10',
        Supplier: 'GreenBoost LLC',
        Item: 'Organic Fertilizer B',
        Quantity: 1500,
        UnitPrice: 84 * 2,
        TotalPrice: 126000 * 2,
        Notes: 'Monthly supply for autumn orchards',
      },
      {
        TransactionID: 'OFT042',
        Division: 'Organic Fruits',
        Date: '2024-02-11',
        Supplier: 'EcoFertilizer Co.',
        Item: 'Organic Fertilizer C',
        Quantity: 1350,
        UnitPrice: 94 * 2,
        TotalPrice: 126900 * 2,
        Notes: 'Special blend for citrus fruits',
      },
      {
        TransactionID: 'OFT043',
        Division: 'Organic Fruits',
        Date: '2024-02-12',
        Supplier: 'FertileGrow Inc.',
        Item: 'Organic Fertilizer A',
        Quantity: 1900,
        UnitPrice: 76 * 2,
        TotalPrice: 144400 * 2,
        Notes: 'Monthly supply for spring orchards',
      },
      {
        TransactionID: 'OFT044',
        Division: 'Organic Fruits',
        Date: '2024-02-13',
        Supplier: 'GreenBoost LLC',
        Item: 'Organic Fertilizer B',
        Quantity: 1550,
        UnitPrice: 86 * 2,
        TotalPrice: 133300 * 2,
        Notes: 'Additional supply for summer orchards',
      },
      {
        TransactionID: 'OFT045',
        Division: 'Organic Fruits',
        Date: '2024-02-14',
        Supplier: 'EcoFertilizer Co.',
        Item: 'Organic Fertilizer C',
        Quantity: 1400,
        UnitPrice: 96 * 2,
        TotalPrice: 134400 * 2,
        Notes: 'Special blend for fruit yield',
      },
      {
        TransactionID: 'OFT046',
        Division: 'Organic Fruits',
        Date: '2024-02-15',
        Supplier: 'FertileGrow Inc.',
        Item: 'Organic Fertilizer A',
        Quantity: 1950,
        UnitPrice: 78 * 2,
        TotalPrice: 152100 * 2,
        Notes: 'Monthly supply for summer orchards',
      },
      {
        TransactionID: 'OFT047',
        Division: 'Organic Fruits',
        Date: '2024-02-16',
        Supplier: 'GreenBoost LLC',
        Item: 'Organic Fertilizer B',
        Quantity: 1600,
        UnitPrice: 88 * 2,
        TotalPrice: 140800 * 2,
        Notes: 'Monthly supply for autumn orchards',
      },
      {
        TransactionID: 'OFT048',
        Division: 'Organic Fruits',
        Date: '2024-02-17',
        Supplier: 'EcoFertilizer Co.',
        Item: 'Organic Fertilizer C',
        Quantity: 1450,
        UnitPrice: 98 * 2,
        TotalPrice: 142100 * 2,
        Notes: 'Special blend for citrus fruits',
      },
      {
        TransactionID: 'OFT049',
        Division: 'Organic Fruits',
        Date: '2024-02-18',
        Supplier: 'FertileGrow Inc.',
        Item: 'Organic Fertilizer A',
        Quantity: 2000,
        UnitPrice: 80 * 2,
        TotalPrice: 160000 * 2,
        Notes: 'Monthly supply for spring orchards',
      },
    ],
  },
];

@Controller('tools/resource_similarity_analysis')
export class ResourceSimilarityAnalysisController {
  @Get()
  async getDivisionData() {
    console.log('divisionData', divisionData);
    return divisionData;
  }
}
