export const forecast_data_properties = {
  type: 'object',
  properties: {
    data_type: {
      type: 'string',
      description: 'Type of data to forecast',
      enum: [
        'sales',
        'revenue',
        'profit',
        'expenses',
        'inventory',
        'net_income',
        'cash_flows',
        'assets',
        'liabilities',
        'equity',
        'income_statement',
        'balance_sheet',
        'cash_flow_statement',
      ],
    },
    data: {
      type: 'object',
      description: 'Specific data related to the forecast',
      oneOf: [
        {
          title: 'Revenue Data',
          properties: {
            data_type: { const: 'revenue' },
            Date: { type: 'string', description: 'Date of data entry' },
            Product_Sales: {
              type: 'number',
              description: 'Sales from products',
            },
            Service_Sales: {
              type: 'number',
              description: 'Sales from services',
            },
            Total_Sales: { type: 'number', description: 'Total sales' },
            Cost_of_Sales_Products: {
              type: 'number',
              description: 'Cost of products sold',
            },
            Cost_of_Sales_Services: {
              type: 'number',
              description: 'Cost of services provided',
            },
            Gross_Margin: { type: 'number', description: 'Gross margin' },
            Operating_Income: {
              type: 'number',
              description: 'Operating income',
            },
            Net_Income: { type: 'number', description: 'Net income' },
            Basic_EPS: {
              type: 'number',
              description: 'Earnings per share (basic)',
            },
            Diluted_EPS: {
              type: 'number',
              description: 'Earnings per share (diluted)',
            },
          },
          required: ['Date', 'Total_Sales', 'Gross_Margin', 'Net_Income'],
        },
        {
          title: 'Net Income Data',
          properties: {
            data_type: { const: 'net_income' },
            Date: { type: 'string', description: 'Date of data entry' },
            Net_Income: { type: 'number', description: 'Net income' },
            Basic_EPS: {
              type: 'number',
              description: 'Earnings per share (basic)',
            },
            Diluted_EPS: {
              type: 'number',
              description: 'Earnings per share (diluted)',
            },
          },
          required: ['Date', 'Net_Income'],
        },
        {
          title: 'Cash Flow Data',
          properties: {
            data_type: { const: 'cash_flows' },
            Date: { type: 'string', description: 'Date of data entry' },
            Operating_Activities: {
              type: 'number',
              description: 'Cash generated by operating activities',
            },
            Investing_Activities: {
              type: 'number',
              description: 'Cash generated by investing activities',
            },
            Financing_Activities: {
              type: 'number',
              description: 'Cash used in financing activities',
            },
            Net_Increase_in_Cash: {
              type: 'number',
              description: 'Net increase in cash and cash equivalents',
            },
          },
          required: [
            'Date',
            'Operating_Activities',
            'Investing_Activities',
            'Financing_Activities',
          ],
        },
        {
          title: 'Asset Data',
          properties: {
            data_type: { const: 'assets' },
            Date: { type: 'string', description: 'Date of data entry' },
            Current_Assets: {
              type: 'number',
              description: 'Total current assets',
            },
            Non_Current_Assets: {
              type: 'number',
              description: 'Total non-current assets',
            },
            Total_Assets: { type: 'number', description: 'Total assets' },
          },
          required: ['Date', 'Total_Assets'],
        },
        {
          title: 'Liabilities Data',
          properties: {
            data_type: { const: 'liabilities' },
            Date: { type: 'string', description: 'Date of data entry' },
            Current_Liabilities: {
              type: 'number',
              description: 'Total current liabilities',
            },
            Non_Current_Liabilities: {
              type: 'number',
              description: 'Total non-current liabilities',
            },
            Total_Liabilities: {
              type: 'number',
              description: 'Total liabilities',
            },
          },
          required: ['Date', 'Total_Liabilities'],
        },
        {
          title: 'Equity Data',
          properties: {
            data_type: { const: 'equity' },
            Date: { type: 'string', description: 'Date of data entry' },
            Common_Stock: { type: 'number', description: 'Common stock value' },
            Retained_Earnings: {
              type: 'number',
              description: 'Retained earnings',
            },
            Accumulated_Other_Comprehensive_Loss: {
              type: 'number',
              description: 'Accumulated other comprehensive loss',
            },
            Total_Shareholders_Equity: {
              type: 'number',
              description: "Total shareholders' equity",
            },
          },
          required: ['Date', 'Total_Shareholders_Equity'],
        },
        {
          title: 'Income Statement Data',
          properties: {
            data_type: { const: 'income_statement' },
            Date: { type: 'string', description: 'Date of data entry' },
            Revenue: { type: 'number', description: 'Total revenue' },
            Cost_of_Revenue: {
              type: 'number',
              description: 'Cost of revenue',
            },
            Gross_Profit: { type: 'number', description: 'Gross profit' },
            Operating_Expenses: {
              type: 'number',
              description: 'Total operating expenses',
            },
            Operating_Income: {
              type: 'number',
              description: 'Operating income',
            },
            Net_Income: { type: 'number', description: 'Net income' },
          },
          required: ['Date', 'Revenue', 'Gross_Profit', 'Net_Income'],
        },
        {
          title: 'Balance Sheet Data',
          properties: {
            data_type: { const: 'balance_sheet' },
            Date: { type: 'string', description: 'Date of data entry' },
            Total_Assets: { type: 'number', description: 'Total assets' },
            Total_Liabilities: {
              type: 'number',
              description: 'Total liabilities',
            },
            Total_Equity: { type: 'number', description: 'Total equity' },
          },
          required: [
            'Date',
            'Total_Assets',
            'Total_Liabilities',
            'Total_Equity',
          ],
        },
        {
          title: 'Cash Flow Statement Data',
          properties: {
            data_type: { const: 'cash_flow_statement' },
            Date: { type: 'string', description: 'Date of data entry' },
            Net_Cash_Provided_by_Operating_Activities: {
              type: 'number',
              description: 'Net cash provided by operating activities',
            },
            Net_Cash_Used_in_Investing_Activities: {
              type: 'number',
              description: 'Net cash used in investing activities',
            },
            Net_Cash_Used_in_Financing_Activities: {
              type: 'number',
              description: 'Net cash used in financing activities',
            },
            Effect_of_Exchange_Rate_Changes_on_Cash: {
              type: 'number',
              description: 'Effect of exchange rate changes on cash',
            },
            Net_Change: {
              type: 'number',
              description: 'Net change in cash and cash equivalents',
            },
          },
          required: [
            'Date',
            'Net_Cash_Provided_by_Operating_Activities',
            'Net_Cash_Used_in_Investing_Activities',
            'Net_Cash_Used_in_Financing_Activities',
            'Net_Change',
          ],
        },
      ],
    },
  },
  required: ['data_type', 'data'],
  additionalProperties: false,
};

export const financial_data_point_commit = {
  type: 'function',
  function: {
    name: 'financial_data_point_commit',
    description: `
    Use this tool to commit a financial data point to the database.
    Enter the financial data point to commit to the database.
    `,
    parameters: {
      $schema: 'http://json-schema.org/draft-07/schema#',
      title: 'Financial Data Point Commit',
      description:
        'Commit a financial data point to the database. This is a financial data point that is committed to the database.',
      type: 'object',
      properties: {
        datum: {
          ...forecast_data_properties,
        },
        date: {
          type: 'string',
          description: 'Date of the financial data point',
        },
        company: {
          type: 'string',
          description: 'Company of the financial data point',
        },
        address: {
          type: 'object',
          description:
            'Address of the financial data point. Enter N/F if not found.',
          properties: {
            street: {
              type: 'string',
              description: 'Street of the address',
            },
            city: {
              type: 'string',
              description: 'City of the address',
            },
            state: {
              type: 'string',
              description: 'State of the address',
            },
            zip: {
              type: 'string',
              description: 'Zip of the address',
            },
          },
          required: ['street', 'city', 'state', 'zip'],
          additionalProperties: false,
        },
        ticker: {
          type: 'string',
          description:
            'Ticker of the financial data point. This is the stock symbol. If this company is not a public company then you can use the company name.',
        },
        period: {
          type: 'string',
          enum: ['month', 'year', 'quarter', 'day', 'hour', 'minute'],
          description:
            'Period Span of the financial data point. Only pick from the list of options. Do not make up a period span.',
        },
        summary: {
          type: 'string',
          description:
            'Descriptive summary of the financial data point to be displayed in the UI. Be complete and concise. Reiterate the data point in the summary.',
        },
        sentiment: {
          type: 'number',
          description:
            'THIS IS A REQUIRED FIELD: Sentiment of the financial data point source material. Use a number between 0 and 1. 0 is very negative, .5 is neutral, and 1 is extremely positive. Numbers can be any decimal in between.',
          minimum: 0,
          maximum: 1,
          default: 0.5,
        },
      },
    },
    required: [
      'data',
      'date',
      'period',
      'company',
      'ticker',
      'address',
      'summary',
      'sentiment',
    ],
    additionalProperties: false,
  },
};
